#!/usr/bin/env bash

set -euo pipefail

REPOSITORY="${XYVC_REPOSITORY:-jiansongy/xiaoyuanvc-website}"
GITHUB_SHA="${XYVC_GITHUB_SHA:?XYVC_GITHUB_SHA is required}"
LIVE_ROOT="/var/www/xiaoyuanvc"
DEPLOY_PARENT="/var/www"
MIN_FREE_KB=1048576
NODE_VERSION="v22.23.1"

if [[ ! "$GITHUB_SHA" =~ ^[0-9a-f]{40}$ ]]; then
  echo "XYVC_GITHUB_SHA must be a 40-character lowercase commit SHA." >&2
  exit 2
fi

WORK_DIR="$(mktemp -d /tmp/xyvc-sync.XXXXXX)"
RELEASE_DIR="$DEPLOY_PARENT/.xyvc-release-${GITHUB_SHA}-$$"
BACKUP_DIR="$DEPLOY_PARENT/.xyvc-backup-${GITHUB_SHA}-$$"
FAILED_DIR="$DEPLOY_PARENT/.xyvc-failed-${GITHUB_SHA}-$$"
SWAPPED=0
LIVE_MOVED=0
PRESERVE_RELEASE=0

remove_managed_tree() {
  local target="$1"
  case "$target" in
    /tmp/xyvc-sync.*|/var/www/.xyvc-release-*|/var/www/.xyvc-backup-*|/var/www/.xyvc-failed-*)
      if [[ -e "$target" ]]; then
        rm -rf -- "$target"
      fi
      ;;
    *)
      echo "Refusing to remove unmanaged path: $target" >&2
      return 1
      ;;
  esac
}

cleanup() {
  local status=$?
  trap - EXIT

  if (( status != 0 && LIVE_MOVED == 1 )); then
    echo "Deployment failed while the live path was empty; attempting immediate recovery." >&2
    if mv "$BACKUP_DIR" "$LIVE_ROOT"; then
      LIVE_MOVED=0
      echo "Previous release returned to the live path." >&2
    elif mv "$RELEASE_DIR" "$LIVE_ROOT"; then
      LIVE_MOVED=0
      echo "New release returned to the live path as a safety fallback." >&2
    else
      PRESERVE_RELEASE=1
      echo "Automatic recovery failed; preserving both candidate trees." >&2
      echo "Manual recovery required: $RELEASE_DIR and $BACKUP_DIR" >&2
    fi
  fi

  if (( status != 0 && SWAPPED == 1 )); then
    echo "Deployment failed after the live swap; restoring the previous release." >&2
    if [[ ! -e "$BACKUP_DIR" ]]; then
      echo "Rollback backup is missing; preserving the current live tree." >&2
    elif [[ -e "$LIVE_ROOT" ]] && ! mv "$LIVE_ROOT" "$FAILED_DIR"; then
      echo "Could not move the failed release aside; preserving live and backup trees." >&2
    elif mv "$BACKUP_DIR" "$LIVE_ROOT"; then
      echo "Previous release restored." >&2
      remove_managed_tree "$FAILED_DIR" || true
    else
      echo "Could not restore the previous release; preserving the backup tree." >&2
      if [[ ! -e "$LIVE_ROOT" && -e "$FAILED_DIR" ]]; then
        if mv "$FAILED_DIR" "$LIVE_ROOT"; then
          echo "The new release was returned to the live path as a safety fallback." >&2
        else
          echo "Manual recovery required: $FAILED_DIR and $BACKUP_DIR" >&2
        fi
      fi
    fi
  fi

  remove_managed_tree "$WORK_DIR" || true
  if (( PRESERVE_RELEASE == 0 )); then
    remove_managed_tree "$RELEASE_DIR" || true
  fi
  if (( status == 0 )); then
    remove_managed_tree "$BACKUP_DIR" || true
  fi
  exit "$status"
}
trap cleanup EXIT

# ---- www nginx 301 重定向（AI 员工面试工具/指南已下架 → /resources/） ----
# 仅在 nginx 站点配置的 www server 块内注入 include；幂等；nginx -t 失败自动回滚，绝不影响站点可用性。
WWW_REDIRECTS_CONF="/etc/nginx/xyvc-www-redirects.conf"
WWW_REDIRECTS_INCLUDE="include /etc/nginx/xyvc-www-redirects.conf;"

apply_www_redirects() {
  local www_conf
  www_conf="$(grep -rlE 'server_name[[:space:]]+www\.xiaoyuanvc\.com' /etc/nginx/ 2>/dev/null | head -n1 || true)"
  if [[ -z "$www_conf" ]]; then
    echo "[nginx-redirects] WARN: 未找到含 server_name www.xiaoyuanvc.com 的 nginx 配置，跳过重定向。" >&2
    return 0
  fi

  if ! cat > "$WWW_REDIRECTS_CONF" <<'NGINX'
    # Generated by xyvc-sync.sh — AI 员工面试工具与指南文章已下架，旧链接 301 到资源中心
    location = /resources/ai-ready-check              { return 301 /resources/; }
    location = /resources/ai-ready-check.html         { return 301 /resources/; }
    location = /resources/ai-employee-interview-guide { return 301 /resources/; }
    location = /resources/ai-employee-interview-guide.html { return 301 /resources/; }
NGINX
  then
    echo "[nginx-redirects] WARN: 无法写入 $WWW_REDIRECTS_CONF，跳过重定向。" >&2
    return 0
  fi

  if grep -Fq "$WWW_REDIRECTS_INCLUDE" "$www_conf"; then
    echo "[nginx-redirects] www server 块已包含重定向 include，跳过注入。"
  elif grep -qE 'server_name[[:space:]]+www\.xiaoyuanvc\.com' "$www_conf"; then
    if ! awk -v inc="    $WWW_REDIRECTS_INCLUDE" '
        { print }
        /server_name[[:space:]]+www\.xiaoyuanvc\.com/ && !inserted { print inc; inserted=1 }
      ' "$www_conf" > "$www_conf.new"; then
      echo "[nginx-redirects] WARN: 无法写入临时配置，跳过重定向。" >&2
      rm -f "$www_conf.new"
      rm -f "$WWW_REDIRECTS_CONF"
      return 0
    fi
    mv "$www_conf.new" "$www_conf"
  else
    echo "[nginx-redirects] WARN: 无法定位 www server_name 行以注入 include，已删除 include 文件。" >&2
    rm -f "$WWW_REDIRECTS_CONF"
    return 0
  fi

  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true
    echo "[nginx-redirects] 已生效：$WWW_REDIRECTS_CONF"
  else
    echo "[nginx-redirects] WARN: nginx -t 校验失败，回滚本次改动，站点不受影响。" >&2
    nginx -t >&2 || true
    if grep -Fq "$WWW_REDIRECTS_INCLUDE" "$www_conf"; then
      if awk -v drop="$WWW_REDIRECTS_INCLUDE" 'index($0, drop)==0' "$www_conf" > "$www_conf.new"; then
        mv "$www_conf.new" "$www_conf"
      else
        rm -f "$www_conf.new"
      fi
    fi
    rm -f "$WWW_REDIRECTS_CONF"
  fi
}

echo "[1/8] Snapshot current server state"
docker ps || true
npm list -g --depth=0 || true
systemctl list-units --type=service --state=running --no-pager || true
cat /etc/os-release || true
ldd --version 2>&1 | head -1 || true
node --version || true
npm --version || true
df -Pk "$DEPLOY_PARENT"

available_kb="$(df -Pk "$DEPLOY_PARENT" | awk 'NR == 2 { print $4 }')"
if [[ ! "$available_kb" =~ ^[0-9]+$ ]] || (( available_kb < MIN_FREE_KB )); then
  echo "At least 1 GiB of free space is required under $DEPLOY_PARENT." >&2
  exit 1
fi

if [[ ! -d "$LIVE_ROOT" ]]; then
  echo "Expected nginx document root does not exist: $LIVE_ROOT" >&2
  exit 1
fi

echo "[2/8] Provision temporary Node.js $NODE_VERSION"
case "$(uname -m)" in
  x86_64)
    node_arch="x64"
    node_sha256="7a8cb04b4a1df4eaf432125324b81b29a088e73570a23259a8de1c65d07fc129"
    ;;
  aarch64|arm64)
    node_arch="arm64"
    node_sha256="543fa39e57d4c07855939459a323f4deb9a79dd1bb45e6e99458b0f2de10db8d"
    ;;
  *)
    echo "Unsupported server architecture: $(uname -m)" >&2
    exit 1
    ;;
esac

node_archive="node-${NODE_VERSION}-linux-${node_arch}.tar.gz"
node_base_url="https://nodejs.org/dist/${NODE_VERSION}"
curl -fsSL "$node_base_url/$node_archive" -o "$WORK_DIR/$node_archive"
(
  cd "$WORK_DIR"
  printf '%s  %s\n' "$node_sha256" "$node_archive" | sha256sum -c -
  tar -xzf "$node_archive"
)
export PATH="$WORK_DIR/node-${NODE_VERSION}-linux-${node_arch}/bin:$PATH"
node --version
npm --version

echo "[3/8] Download exact source SHA: $GITHUB_SHA"
archive="$WORK_DIR/source.tar.gz"
source_parent="$WORK_DIR/source"
mkdir -p "$source_parent"
curl -fsSL \
  "https://codeload.github.com/${REPOSITORY}/tar.gz/${GITHUB_SHA}" \
  -o "$archive"
tar -xzf "$archive" -C "$source_parent"

source_dir="$(find "$source_parent" -mindepth 1 -maxdepth 1 -type d -print -quit)"
if [[ -z "$source_dir" || ! -f "$source_dir/build.sh" || ! -f "$source_dir/learn-src/package-lock.json" ]]; then
  echo "Downloaded source archive does not contain the expected project structure." >&2
  exit 1
fi

echo "[4/8] Build complete dist tree"
(
  cd "$source_dir"
  bash build.sh
)

echo "[5/8] Validate build output"
required_files=(
  "dist/index.html"
  "dist/learn/crypto-vc/index.html"
  "dist/learn/digital-startup/index.html"
)
for required_file in "${required_files[@]}"; do
  if [[ ! -s "$source_dir/$required_file" ]]; then
    echo "Missing required build output: $required_file" >&2
    exit 1
  fi
done
grep -Fq '京ICP备2021017602号-1' "$source_dir/dist/index.html"
grep -Fq '京公网安备11010802035175号' "$source_dir/dist/index.html"

mkdir "$RELEASE_DIR"
cp -a "$source_dir/dist/." "$RELEASE_DIR/"
release_file_count="$(find "$RELEASE_DIR" -type f | wc -l | tr -d ' ')"
echo "Prepared $release_file_count files for release."

echo "[6/8] Replace nginx document root"
mv "$LIVE_ROOT" "$BACKUP_DIR"
LIVE_MOVED=1
mv "$RELEASE_DIR" "$LIVE_ROOT"
LIVE_MOVED=0
SWAPPED=1

# 在新文档根生效后，注入 www 的下架重定向（幂等、失败回滚，绝不影响站点可用性）
apply_www_redirects

echo "[7/8] Verify local nginx origin"
origin=(curl --noproxy '*' --silent --show-error --resolve www.xiaoyuanvc.com:443:127.0.0.1)

verify_page() {
  local path="$1"
  local marker="$2"
  local body_file="$WORK_DIR/response.html"
  local status

  status="$("${origin[@]}" --output "$body_file" --write-out '%{http_code}' "https://www.xiaoyuanvc.com$path")"
  if [[ "$status" != "200" ]]; then
    echo "Local smoke test failed for $path: HTTP $status" >&2
    return 1
  fi
  grep -Fq "$marker" "$body_file"
}

# 下架资源的重定向：非致命，仅告警，避免阻断内容部署
verify_redirect_nonfatal() {
  local path="$1"
  local status
  status="$("${origin[@]}" --silent --show-error --output /dev/null --write-out '%{http_code}' "https://www.xiaoyuanvc.com$path")"
  if [[ "$status" != "301" ]]; then
    echo "WARN: expected HTTP 301 for $path, got $status (redirect may not have been applied)." >&2
  fi
}

verify_page "/" "京ICP备2021017602号-1"
verify_page "/learn/crypto-vc/" "加密创投教程"
verify_page "/learn/digital-startup/" "数字创业教程"
verify_redirect_nonfatal "/resources/ai-ready-check"
verify_redirect_nonfatal "/resources/ai-employee-interview-guide"

missing_path="/deployment-smoke-missing-${GITHUB_SHA}"
missing_status="$("${origin[@]}" --output /dev/null --write-out '%{http_code}' "https://www.xiaoyuanvc.com$missing_path")"
if [[ "$missing_status" != "404" ]]; then
  echo "Expected HTTP 404 for $missing_path, got $missing_status." >&2
  exit 1
fi

echo "[8/8] Finalize release"
SWAPPED=0
remove_managed_tree "$BACKUP_DIR"
echo "DONE-SYNC SHA=$GITHUB_SHA FILES=$release_file_count"
